version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: 'dead_drop_db'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: deaddrop

  backend:
    build: DeadDrop.api/
    container_name: 'dead_drop_api'
    ports:
      - '8080:8080'
    # environment:
    #   - NODE_ENV="development"
    #   - DATABASE_HOST="database"
    #   - POSTGRES_PASSWORD="postgres"
    #   - POSTGRES_USER="postgres"
    #   - POSTGRES_PORT="5432"
    #   - POSTGRES_DB="deaddrop"
    depends_on:
      - database

  frontend: 
    build: DeadDrop.ui/
    container_name: 'dead_drop_ui'
    ports: 
      - '3000:3000'
    depends_on:
      - backend
  