CREATE TABLE dead_drops (
    id VARCHAR PRIMARY KEY,
    title VARCHAR,
    msg BYTEA,
    att BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);